    <main>
        <!-- Chargement du template PHTML spécifié par le programme PHP -->
        <!-- Page d'ajout d'un article -->
<h2><i class="fa fa-pencil"></i> Rédiger un nouvel article</h2>

<!-- Formulaire de saisie d'un nouvel article -->
<form class="generic-form" action="add_post.php" method="post">
    <fieldset>
        <legend><i class="fa fa-sticky-note-o"></i> Nouvel article</legend>
        <ul>
            <li>
                <label for="title">Titre :</label>
                <input type="text" id="title" name="title">
            </li>
            <li>
                <label class="textarea" for="contents">Article :</label>
                <textarea id="contents" name="contents" rows="15"></textarea>
            </li>
            <li>
                <label for="author">Auteur :</label>
                <select id="author" name="author">
                    <?php foreach ($authors as $index=>$auteur) {?>

                        <option value="<?= $auteur['Id'] ?>" > <?= $auteur['FirstName'] ?></option>

                    <?php }?>

                                    </select>
            </li>
            <li>
                <label for="category">Catégorie :</label>
                <select id="category" name="category">
                    <?php foreach ($categories as $index=>$categorie) {?>

                        <option value="<?= $categorie['Id'] ?>" > <?= $categorie['Name'] ?></option>

                    <?php }?>
                </select>
            </li>
            <li>
                <button class="button button-primary" type="submit">Enregistrer</button>
                <a class="button button-cancel" href="index.php">Annuler</a>
            </li>
        </ul>
    </fieldset>
</form></main>