<?php if(array_key_exists('user', $_SESSION) == false) { ?>

<h2>HOPHOPHOP</h2>

<?php } else { ?>


<main>
        <!-- Chargement du template PHTML spécifié par le programme PHP -->
        <!-- Page d'édition d'un article -->
<h2><i class="fa fa-pencil"></i> Editer un article</h2>

<!-- Formulaire de mise à jour d'un article -->
<form class="generic-form" action="edit_post.php?id=<?= $articleId?>" method="post">

    <!-- Utilisation d'un champ caché pour spécifier à quel article rattacher le commentaire -->
    <input type="hidden" name="postId" value="<br />
<font size='1'><table class='xdebug-error xe-notice' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan=" 5"="">


    <fieldset>
        <legend><i class="fa fa-sticky-note-o"></i> Article</legend>
        <ul>
            <li>
                <label for="title">Titre :</label>
                <input type="text" id="title" name="title" value="stuptuytu">
            </li>
            <li>
                <label class="textarea" for="contents">Article :</label>
                <textarea id="contents" name="contents" rows="15">blablablalbabab</textarea>
            </li>
            <li>
                <button class="button button-primary" type="submit">Mettre à jour</button>
                <a class="button button-cancel" href="index.php">Annuler</a>
            </li>
        </ul>
    </fieldset>
</form>    </main>

<?php } ?>