

<form id="register-form" action="register.php" method="POST">
	<h2><label>Nom</label></h2>
    <input type="text" name="LastName"/>
    <h2><label>Prénom</label></h2>
    <input type="text" name="FirstName"/>
    <h2><label>Email</label></h2>
    <input type="text" name="Email"/>
    <h2><label>Password</label></h2>
    <input type="text" name="Password"/>

	<input type="submit" value="envoyer"/>

</form>