<!-- Message de notification -->

<!-- Code HTML à écrire -->


<!-- Liste des aliments -->
<table class="generic-table meal-list">
    <caption>Carte du restaurant</caption>
    <tbody>

       <?php 



       foreach ($meals as $meal) { ?>
       <tr>
		<td> <img src="<?= $wwwUrl ?>/images/meals/<?= $meal['Photo'] ?>"</td>
		<td><p><strong> <?= $meal['Name'] ?></strong></p><p> <?= $meal['Description'] ?></p></td>
		<td> <strong><?= number_format($meal['SalePrice'], 2) ?>€</strong></td>



       	<?php } ?>

    </tbody>
</table>