<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
 	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <link rel="stylesheet" href="index.css">
    <title>Traducteur</title>
</head>
<body>
<h1>Traducteur Anglais - Francais</h1>
<section>
	<p>Mot : </p>
	<form action="trad.php" method="post">
	<input type="text" name="word">
	<input type="submit">

</section>
<section>
	<p>Sens de traduction : </p>
	<select name="direction">
		<option value="AnglaisversFrancais">Anglais vers Francais</option> 
 		<option value="FrancaisversAnglais">Francais vers Anglais</option>
	</select>
	</form>

</body>
</html>